server:
  port: 9200
  servlet:
    context-path: /store/v1
spring:
  application:
    name: service-product
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: